# Generated by Django 5.2.11 on 2026-02-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_group_groupmessage_groupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10),
        ),
    ]
